# 异常

# 一、基础知识

- 概念: 程序出现了非预期的情况导致计算机无法处理称为发生了异常
- 运行期间异常: 在程序执行期间发生的异常，如数组越界、空指针、零除
- 处理方式
  - abort()函数: 函数原型位于`cstdlib.h`文件，默认情况会输出错误信息并终止程序
  - 返回错误码: 设置标志位，告诉程序是否发生异常，若存在进行相应的异常处理
  - 异常机制: 关键字`throw`引发异常，`catch`捕获异常并处理异常，`try`标识异常发生的代码块
- C++异常规范
  - 语法

    ```C++
    double harm(double a) throw(bad_thing);     //会引发bad_thing类型的异常
    double marm(double) throw();                //不会引发异常
    ``` 

  - 作用: 告诉程序员是否需要使用try块，告诉编译器是否需要进行运行阶段检查
  - 不推荐使用异常规范
  - C++11关键字noexcept: 修饰原型或定义，声明该函数不会引发异常
  - noexcept(): 判断操作数是否会引发异常

# 二、异常处理方式

- abort()函数
  - 默认功能: 向标准错误流打印错误信息并终止程序
  - 示例程序

    ```C++
    #include <iostream>
    #include <cstdlib>

    double hmean(double a, double b);

    int main() {
        double x, y, z;
        std::cout<<"Enter two numbers: ";
        while (std::cin>>x>>y) {
            z = hmean(x, y);
            std::cout<<"Harmonic mean of"<<x<<" and "<<y<<" is "<<z<<std::endl;
            std::cout<<"Enter next set of numbers <q to quit>:";
        }
        std::cout<<"Bye!\n";
        return 0;
    }

    double mean(double a, double b) {
        if (a == -b) {
            std::cout<< "untenable arguments to hmean()\n";
            std::abort();
        }
        return 2.0 * a * b / (a + b);
    }
    ```

- 返回错误码
  - 方法: 使用标志位指示错误信息
  - 示例程序

    ```C++
    #include <iostream>
    #include <cfloat>

    bool hmean(double a, double b, double* ans);

    int main() {
        double x, y, z;
        std::cout<<"Enter two numbers: ";
        while (std::cin>>x>>y) {
            if (hmean(x, y, &z)) 
                std::cout<<"Harmonic mean of"<<x<<" and "<<y<<" is "<<z<<std::endl;
            else 
                std::cout<<"One value should not be the negative "<<"of the other - try again.\n";
            std::cout<<"Enter next set of numbers <q to quit>:";
        }
        std::cout<<"Bye!\n";
        return 0;
    }

    bool hmean(double a, double b, double* ans) {
        if (a == -b) {
            *ans = DBL_MAX;
            return false;
        }
        *ans = 2.0 * a * b / (a + b);
        return true;
    }
    ```
  
## 三、异常机制

- 关键要素
  - `throw`: `throw 异常对象`，在发生异常的代码处抛出一个异常，对象可以是基本类型或类类型
  - `catch`: `catch (异常类型 变量名) {}`，{}内为异常处理语句，可以存在多个catch块。发生异常时会根据参数列表匹配合适的catch块，并执行异常处理程序。
  - `try`: `try {}`，{}内为可能发生异常的代码块
- 工作流程
  - 首先使用`try`标识可能发生异常的代码块，`throw`在发生异常的代码块处抛出一个异常，异常发生时根据catch的参数列表找到匹配的catch块
  - 若找到则执行该catch块的内容，若没有catch块或未找到则调用`abort()`函数
- 示例代码
  
    ```C++
    // 类类型的异常机制
    #include <iostream>
    #include <cmath>

    // 异常类
    class bad_hmean {
    private:
        double a;
        double b;
    public:
        bad_hmean(double a0=0, double b0=0):a(a0), b(b0){}
        void mesg() {std::cout <<"bad hmean() arguments: a = "<<a<<" b = "<<b<<std::endl;}
    };

    class bad_gmean {
    private:
        double a;
        double b;
    public:
        bad_gmean(double a0=0, double b0=0):a(a0), b(b0){}
        void mesg() {std::cout<<"bad gmean() arguments: a = "<<a<<" b = "<<b<<std::endl;}
    };

    double hmean(double a, double b);
    double gmean(double a, double b);

    int main() {
        double x, y, z;

        std::cout<<"Enter two numbers, <q to quit>: ";
        while (std::cin>>x>>y) {
            try {
                z = hmean(x, y);
                std::cout<<"the harmonic mean of "<<x<<", "<<y<<" is "<<z<<std::endl;
                z = gmean(x, y);
                std::cout<<"the geometric mean of "<<x<<", "<<y<<" is "<<z<<std::endl;
            } catch (bad_hmean& bh) {
                bh.mesg();
                std::cout<<"Try again, <q to quit>: ";
                continue;
            } catch (bad_gmean& bg) {
                bg.mesg();
                std::cout<<"Try again, <q to quit>: ";
                continue;
            }
            std::cout<<"Enter a new pair of numbers, <q to quit>: ";
        }
        std::cout<<"Bye!\n";
        return 0;
    }

    double hmean(double a, double b) {
        if (a == -b)
            throw bad_hmean(a, b);
        return 2.0 * a * b / (a + b);
    }
    double gmean(double a, double b) {
        if (a<=0 || b<=0)
            throw bad_gmean(a, b);
        return std::sqrt(a*b);
    }
    ```

- throw关键字与栈解退
  - throw关键字
    - 工作原理: throw会终止当前程序的运行并找到最近的try的位置，从当前位置开始查找catch块并执行异常处理程序
    - 与return的比较: 二者都会终止当前程序的运行，但return将控制权交给调用进程，throw会回退到try块处
  - 栈解退
    - 函数调用过程
      - 函数调用时栈中会存放函数地址、传入参数以及自动变量，若有函数嵌套则存放被嵌套的函数地址、传入参数以及自动变量
      - 当函数执行返回语句后释放自动变量和传入参数，碰到地址时从地址的下一条命令开始执行。如果存在类对象会自动调用对应的析构函数
    - throw调用过程
        与函数调用类似，但不是碰到返回语句终止而是继续回退并释放变量，如果有类对象调用析构函数，直到找到try块，该过程称为栈解退